# Generated by Django 4.2.25 on 2025-10-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Cart_id',
            new_name='cart_id',
        ),
    ]
